# Generated by Django 5.2.5 on 2025-09-01 13:43

import users.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.TextField(validators=[users.validators.custom_email_validator]),
        ),
    ]
