# Generated by Django 5.2.5 on 2025-09-11 12:03

import users.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.TextField(unique=True, validators=[users.validators.custom_email_validator]),
        ),
    ]
