ACCOUNT_CREATION_SUCCESS_MESSAGE = "your account has been created successfully"
LOG_IN_SUCCESS_MESSAGE = "Logged in successfully"
ERROR_MESSAGE =  "Invalid username or password"
LOGOUT_SUCCESS_MESSAGE = "Logged out successfully"
ACCOUNT_NOT_FOUND_ERROR_MESSAGE = "No account found with this email"
INVALID_EMAIL_MESSAGE = "Invalid email or password"
NOT_AUTHENTICATED = "Not Authenticated"
